# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/dp/zcu106/tpg_dp_live/vivado/tpg_dp_live/tpg_dp_live.srcs/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_proc_ss_0_0/mpsoc_preset_v_proc_ss_0_0.xci
# IP: The module: 'mpsoc_preset_v_proc_ss_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/dp/zcu106/tpg_dp_live/vivado/tpg_dp_live/tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_proc_ss_0_0/bd_0/bd_85a6.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85a6 || ORIG_REF_NAME==bd_85a6} -quiet] -quiet

# IP: d:/dp/zcu106/tpg_dp_live/vivado/tpg_dp_live/tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_proc_ss_0_0/bd_0/ip/ip_0/bd_85a6_csc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85a6_csc_0 || ORIG_REF_NAME==bd_85a6_csc_0} -quiet] -quiet

# XDC: d:/dp/zcu106/tpg_dp_live/vivado/tpg_dp_live/tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_proc_ss_0_0/bd_0/bd_85a6_ooc.xdc

# XDC: d:/dp/zcu106/tpg_dp_live/vivado/tpg_dp_live/tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_proc_ss_0_0/mpsoc_preset_v_proc_ss_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mpsoc_preset_v_proc_ss_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/dp/zcu106/tpg_dp_live/vivado/tpg_dp_live/tpg_dp_live.srcs/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_proc_ss_0_0/mpsoc_preset_v_proc_ss_0_0.xci
# IP: The module: 'mpsoc_preset_v_proc_ss_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/dp/zcu106/tpg_dp_live/vivado/tpg_dp_live/tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_proc_ss_0_0/bd_0/bd_85a6.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85a6 || ORIG_REF_NAME==bd_85a6} -quiet] -quiet

# IP: d:/dp/zcu106/tpg_dp_live/vivado/tpg_dp_live/tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_proc_ss_0_0/bd_0/ip/ip_0/bd_85a6_csc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_85a6_csc_0 || ORIG_REF_NAME==bd_85a6_csc_0} -quiet] -quiet

# XDC: d:/dp/zcu106/tpg_dp_live/vivado/tpg_dp_live/tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_proc_ss_0_0/bd_0/bd_85a6_ooc.xdc

# XDC: d:/dp/zcu106/tpg_dp_live/vivado/tpg_dp_live/tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_proc_ss_0_0/mpsoc_preset_v_proc_ss_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mpsoc_preset_v_proc_ss_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
