// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mpsoc_preset_v_tpg_0_0_tpgBackground (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        height,
        width,
        bckgndId,
        ZplateHorContStart,
        ZplateHorContDelta,
        ZplateVerContStart,
        ZplateVerContDelta,
        dpDynamicRange,
        dpYUVCoef,
        motionSpeed,
        colorFormat,
        bckgndYUV_din,
        bckgndYUV_num_data_valid,
        bckgndYUV_fifo_cap,
        bckgndYUV_full_n,
        bckgndYUV_write,
        s
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] height;
input  [15:0] width;
input  [7:0] bckgndId;
input  [15:0] ZplateHorContStart;
input  [15:0] ZplateHorContDelta;
input  [15:0] ZplateVerContStart;
input  [15:0] ZplateVerContDelta;
input  [7:0] dpDynamicRange;
input  [7:0] dpYUVCoef;
input  [7:0] motionSpeed;
input  [7:0] colorFormat;
output  [23:0] bckgndYUV_din;
input  [4:0] bckgndYUV_num_data_valid;
input  [4:0] bckgndYUV_fifo_cap;
input   bckgndYUV_full_n;
output   bckgndYUV_write;
input  [31:0] s;

reg ap_done;
reg ap_idle;
reg start_write;
reg bckgndYUV_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [7:0] rampStart;
reg   [15:0] rampVal_1;
reg   [7:0] rampVal;
reg   [7:0] hBarSel_4_0;
reg   [15:0] zonePlateVAddr;
reg   [2:0] vBarSel;
reg   [2:0] hBarSel_0;
reg   [15:0] hdata;
reg   [7:0] vBarSel_2;
reg   [2:0] hBarSel_3_0;
reg   [15:0] rampVal_2;
reg   [0:0] vBarSel_1;
reg   [2:0] hBarSel_5_0;
reg    ap_block_state1;
wire   [0:0] cmp2_i224_fu_613_p2;
reg   [0:0] cmp2_i224_reg_1183;
wire   [7:0] conv2_i_i10_i229_fu_619_p3;
reg   [7:0] conv2_i_i10_i229_reg_1188;
wire   [0:0] not_cmp2_i224_fu_627_p2;
reg   [0:0] not_cmp2_i224_reg_1193;
wire   [7:0] conv2_i_i10_i234_fu_633_p3;
reg   [7:0] conv2_i_i10_i234_reg_1198;
wire   [4:0] conv2_i_i_i236_cast_cast_fu_641_p3;
reg   [4:0] conv2_i_i_i236_cast_cast_reg_1203;
wire   [2:0] conv2_i_i10_i252_cast_cast_cast_cast_fu_649_p3;
reg   [2:0] conv2_i_i10_i252_cast_cast_cast_cast_reg_1208;
wire   [7:0] conv2_i_i_i254_fu_657_p3;
reg   [7:0] conv2_i_i_i254_reg_1213;
wire   [7:0] pix_fu_665_p3;
reg   [7:0] pix_reg_1218;
wire   [7:0] pix_5_fu_673_p3;
reg   [7:0] pix_5_reg_1223;
wire   [9:0] barWidthMinSamples_fu_701_p2;
reg   [9:0] barWidthMinSamples_reg_1228;
wire   [0:0] icmp_fu_727_p2;
reg   [0:0] icmp_reg_1233;
reg   [10:0] barWidth_reg_1238;
wire   [10:0] sub_i_i_i_fu_763_p2;
reg   [10:0] sub_i_i_i_reg_1244;
reg   [7:0] rampStart_load_reg_1249;
reg   [15:0] y_3_reg_1255;
wire    ap_CS_fsm_state2;
wire   [7:0] trunc_ln518_fu_915_p1;
reg   [7:0] trunc_ln518_reg_1261;
wire   [0:0] cmp12_i_fu_931_p2;
reg   [0:0] cmp12_i_reg_1269;
wire   [0:0] icmp_ln518_fu_920_p2;
reg   [1:0] Sel_reg_1274;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_start;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_done;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_idle;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_ready;
wire   [23:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_bckgndYUV_din;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_bckgndYUV_write;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_3_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_3_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_3_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_3_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_3_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_4_0_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_4_0_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_zonePlateVAddr_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_zonePlateVAddr_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_0_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_0_loc_1_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hdata_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hdata_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hdata_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hdata_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hdata_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hdata_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_3_0_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_3_0_loc_1_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_2_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_2_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_2_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_2_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_3_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_5_0_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_5_0_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_2_0_0_0460_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_2_0_0_0460_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_1_0_0_0458_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_1_0_0_0458_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_0_0_0_0456_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_0_0_0_0456_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_4_0;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_4_0_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_zonePlateVAddr;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_zonePlateVAddr_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_0;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_0_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_3_0;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_3_0_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_2_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_5_0;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_5_0_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_1_ap_vld;
wire   [0:0] ap_phi_mux_rampVal_3_flag_0_phi_fu_400_p4;
reg   [0:0] rampVal_3_flag_0_reg_396;
wire    ap_CS_fsm_state4;
wire   [0:0] ap_phi_mux_hdata_flag_0_phi_fu_412_p4;
reg   [0:0] hdata_flag_0_reg_408;
wire   [0:0] ap_phi_mux_rampVal_2_flag_0_phi_fu_424_p4;
reg   [0:0] rampVal_2_flag_0_reg_420;
reg    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [15:0] rampVal_3_new_0_fu_314;
reg   [15:0] rampVal_3_loc_0_fu_310;
reg   [15:0] rampVal_loc_0_fu_306;
reg   [7:0] hBarSel_4_0_loc_0_fu_302;
reg   [15:0] zonePlateVAddr_loc_0_fu_298;
reg   [7:0] vBarSel_loc_0_fu_294;
reg   [7:0] hBarSel_0_loc_0_fu_290;
reg   [15:0] hdata_new_0_fu_286;
reg   [15:0] hdata_loc_0_fu_282;
reg   [7:0] vBarSel_2_loc_0_fu_278;
reg   [7:0] hBarSel_3_0_loc_0_fu_274;
reg   [15:0] rampVal_2_new_0_fu_270;
reg   [15:0] rampVal_2_loc_0_fu_266;
reg   [7:0] vBarSel_3_loc_0_fu_262;
reg   [7:0] hBarSel_5_0_loc_0_fu_258;
reg   [7:0] p_0_2_0_0_0461_lcssa470_fu_250;
reg   [7:0] p_0_1_0_0_0459_lcssa467_fu_246;
reg   [7:0] p_0_0_0_0_0457_lcssa464_fu_242;
wire   [7:0] add_ln705_fu_954_p2;
reg   [15:0] y_fu_254;
wire   [15:0] add_ln518_fu_925_p2;
wire   [7:0] zext_ln518_fu_841_p1;
wire   [7:0] zext_ln1730_fu_833_p1;
wire   [7:0] zext_ln1610_fu_821_p1;
wire   [7:0] zext_ln1493_fu_805_p1;
wire   [7:0] zext_ln1367_fu_797_p1;
wire   [15:0] zext_ln1212_fu_781_p1;
wire   [13:0] empty_fu_681_p1;
wire   [13:0] add2_i_fu_685_p2;
wire   [9:0] p_cast_fu_691_p4;
wire   [13:0] empty_73_fu_707_p1;
wire   [6:0] tmp_fu_717_p4;
wire   [13:0] add_i_fu_733_p2;
wire   [13:0] add5_i_fu_711_p2;
wire   [9:0] tmp_4_fu_749_p4;
wire   [10:0] barHeight_cast_cast_fu_759_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 rampStart = 8'd0;
#0 rampVal_1 = 16'd0;
#0 rampVal = 8'd0;
#0 hBarSel_4_0 = 8'd0;
#0 zonePlateVAddr = 16'd0;
#0 vBarSel = 3'd0;
#0 hBarSel_0 = 3'd0;
#0 hdata = 16'd0;
#0 vBarSel_2 = 8'd0;
#0 hBarSel_3_0 = 3'd0;
#0 rampVal_2 = 16'd0;
#0 vBarSel_1 = 1'd0;
#0 hBarSel_5_0 = 3'd0;
#0 grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_start_reg = 1'b0;
end

mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2 grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_start),
    .ap_done(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_done),
    .ap_idle(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_idle),
    .ap_ready(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_ready),
    .bckgndYUV_din(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_bckgndYUV_din),
    .bckgndYUV_num_data_valid(5'd0),
    .bckgndYUV_fifo_cap(5'd0),
    .bckgndYUV_full_n(bckgndYUV_full_n),
    .bckgndYUV_write(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_bckgndYUV_write),
    .rampVal_3_flag_0(rampVal_3_flag_0_reg_396),
    .hdata_flag_0(hdata_flag_0_reg_408),
    .rampVal_2_flag_0(rampVal_2_flag_0_reg_420),
    .loopWidth(width),
    .pix_5(pix_5_reg_1223),
    .pix(pix_reg_1218),
    .conv2_i_i_i254(conv2_i_i_i254_reg_1213),
    .conv2_i_i_i236_cast_cast(conv2_i_i_i236_cast_cast_reg_1203),
    .conv2_i_i_i_cast(not_cmp2_i224_reg_1193),
    .conv2_i_i10_i252_cast_cast_cast_cast(conv2_i_i10_i252_cast_cast_cast_cast_reg_1208),
    .conv2_i_i10_i234(conv2_i_i10_i234_reg_1198),
    .conv2_i_i10_i229(conv2_i_i10_i229_reg_1188),
    .rampStart_1(rampStart_load_reg_1249),
    .Zplate_Hor_Control_Start(ZplateHorContStart),
    .bckgndId_load(bckgndId),
    .cmp2_i224(cmp2_i224_reg_1183),
    .zext_ln1032(rampStart_load_reg_1249),
    .y(y_3_reg_1255),
    .colorFormatLocal(colorFormat),
    .barWidth_cast(barWidth_reg_1238),
    .barWidth(barWidth_reg_1238),
    .Zplate_Hor_Control_Delta(ZplateHorContDelta),
    .Zplate_Ver_Control_Start(ZplateVerContStart),
    .cmp12_i(cmp12_i_reg_1269),
    .Zplate_Ver_Control_Delta(ZplateVerContDelta),
    .sub_i_i_i(sub_i_i_i_reg_1244),
    .barWidthMinSamples(barWidthMinSamples_reg_1228),
    .loopWidth_cast29(width),
    .loopHeight_cast23(height),
    .zext_ln520(y_3_reg_1255),
    .trunc_ln(trunc_ln518_reg_1261),
    .cmp35_i429(icmp_reg_1233),
    .Sel(Sel_reg_1274),
    .dpDynamicRange_1(dpDynamicRange),
    .dpYUVCoef_1(dpYUVCoef),
    .rampVal_3_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_3_flag_1_out),
    .rampVal_3_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_3_flag_1_out_ap_vld),
    .rampVal_3_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_3_new_1_out),
    .rampVal_3_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_3_new_1_out_ap_vld),
    .rampVal_3_loc_1_out_i(rampVal_3_loc_0_fu_310),
    .rampVal_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_3_loc_1_out_o),
    .rampVal_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_3_loc_1_out_o_ap_vld),
    .rampVal_loc_1_out_i(rampVal_loc_0_fu_306),
    .rampVal_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_loc_1_out_o),
    .rampVal_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_loc_1_out_o_ap_vld),
    .hBarSel_4_0_loc_1_out_i(hBarSel_4_0_loc_0_fu_302),
    .hBarSel_4_0_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_4_0_loc_1_out_o),
    .hBarSel_4_0_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_4_0_loc_1_out_o_ap_vld),
    .zonePlateVAddr_loc_1_out_i(zonePlateVAddr_loc_0_fu_298),
    .zonePlateVAddr_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_zonePlateVAddr_loc_1_out_o),
    .zonePlateVAddr_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_zonePlateVAddr_loc_1_out_o_ap_vld),
    .vBarSel_loc_1_out_i(vBarSel_loc_0_fu_294),
    .vBarSel_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_loc_1_out_o),
    .vBarSel_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_loc_1_out_o_ap_vld),
    .hBarSel_0_loc_1_out_i(hBarSel_0_loc_0_fu_290),
    .hBarSel_0_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_0_loc_1_out_o),
    .hBarSel_0_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_0_loc_1_out_o_ap_vld),
    .hdata_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hdata_flag_1_out),
    .hdata_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hdata_flag_1_out_ap_vld),
    .hdata_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hdata_new_1_out),
    .hdata_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hdata_new_1_out_ap_vld),
    .hdata_loc_1_out_i(hdata_loc_0_fu_282),
    .hdata_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hdata_loc_1_out_o),
    .hdata_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hdata_loc_1_out_o_ap_vld),
    .vBarSel_2_loc_1_out_i(vBarSel_2_loc_0_fu_278),
    .vBarSel_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_2_loc_1_out_o),
    .vBarSel_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_2_loc_1_out_o_ap_vld),
    .hBarSel_3_0_loc_1_out_i(hBarSel_3_0_loc_0_fu_274),
    .hBarSel_3_0_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_3_0_loc_1_out_o),
    .hBarSel_3_0_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_3_0_loc_1_out_o_ap_vld),
    .rampVal_2_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_2_flag_1_out),
    .rampVal_2_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_2_flag_1_out_ap_vld),
    .rampVal_2_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_2_new_1_out),
    .rampVal_2_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_2_new_1_out_ap_vld),
    .rampVal_2_loc_1_out_i(rampVal_2_loc_0_fu_266),
    .rampVal_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_2_loc_1_out_o),
    .rampVal_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_2_loc_1_out_o_ap_vld),
    .vBarSel_3_loc_1_out_i(vBarSel_3_loc_0_fu_262),
    .vBarSel_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_3_loc_1_out_o),
    .vBarSel_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_3_loc_1_out_o_ap_vld),
    .hBarSel_5_0_loc_1_out_i(hBarSel_5_0_loc_0_fu_258),
    .hBarSel_5_0_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_5_0_loc_1_out_o),
    .hBarSel_5_0_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_5_0_loc_1_out_o_ap_vld),
    .p_0_2_0_0_0460_out_i(p_0_2_0_0_0461_lcssa470_fu_250),
    .p_0_2_0_0_0460_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_2_0_0_0460_out_o),
    .p_0_2_0_0_0460_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_2_0_0_0460_out_o_ap_vld),
    .p_0_1_0_0_0458_out_i(p_0_1_0_0_0459_lcssa467_fu_246),
    .p_0_1_0_0_0458_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_1_0_0_0458_out_o),
    .p_0_1_0_0_0458_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_1_0_0_0458_out_o_ap_vld),
    .p_0_0_0_0_0456_out_i(p_0_0_0_0_0457_lcssa464_fu_242),
    .p_0_0_0_0_0456_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_0_0_0_0456_out_o),
    .p_0_0_0_0_0456_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_0_0_0_0456_out_o_ap_vld),
    .rampVal(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal),
    .rampVal_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_ap_vld),
    .hBarSel_4_0(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_4_0),
    .hBarSel_4_0_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_4_0_ap_vld),
    .s(s),
    .zonePlateVAddr(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_zonePlateVAddr),
    .zonePlateVAddr_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_zonePlateVAddr_ap_vld),
    .hBarSel_0(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_0),
    .hBarSel_0_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_0_ap_vld),
    .vBarSel(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel),
    .vBarSel_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_ap_vld),
    .hBarSel_3_0(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_3_0),
    .hBarSel_3_0_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_3_0_ap_vld),
    .vBarSel_2(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_2),
    .vBarSel_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_2_ap_vld),
    .hBarSel_5_0(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_5_0),
    .hBarSel_5_0_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_5_0_ap_vld),
    .vBarSel_1(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_1),
    .vBarSel_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_1_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_920_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_920_p2 == 1'd0))) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_start_reg <= 1'b1;
        end else if ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_ready == 1'b1)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_0_loc_0_fu_290 <= zext_ln1493_fu_805_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_0_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_0_loc_0_fu_290 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_0_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_3_0_loc_0_fu_274 <= zext_ln1610_fu_821_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_3_0_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_3_0_loc_0_fu_274 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_3_0_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_4_0_loc_0_fu_302 <= hBarSel_4_0;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_4_0_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_4_0_loc_0_fu_302 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_4_0_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_5_0_loc_0_fu_258 <= zext_ln518_fu_841_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_5_0_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_5_0_loc_0_fu_258 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_5_0_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hdata_flag_0_reg_408 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hdata_flag_1_out;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hdata_flag_0_reg_408 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hdata_loc_0_fu_282 <= hdata;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hdata_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hdata_loc_0_fu_282 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hdata_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rampVal_2_flag_0_reg_420 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_2_flag_1_out;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_2_flag_0_reg_420 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_2_loc_0_fu_266 <= rampVal_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_2_loc_0_fu_266 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rampVal_3_flag_0_reg_396 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_3_flag_1_out;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_3_flag_0_reg_396 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_3_loc_0_fu_310 <= rampVal_1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_3_loc_1_out_o_ap_vld == 1'b1))) begin
        rampVal_3_loc_0_fu_310 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_loc_0_fu_306 <= zext_ln1212_fu_781_p1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_loc_1_out_o_ap_vld == 1'b1))) begin
        rampVal_loc_0_fu_306 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        vBarSel_2_loc_0_fu_278 <= vBarSel_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel_2_loc_0_fu_278 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        vBarSel_3_loc_0_fu_262 <= zext_ln1730_fu_833_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel_3_loc_0_fu_262 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        vBarSel_loc_0_fu_294 <= zext_ln1367_fu_797_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel_loc_0_fu_294 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_254 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_920_p2 == 1'd0))) begin
        y_fu_254 <= add_ln518_fu_925_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        zonePlateVAddr_loc_0_fu_298 <= zonePlateVAddr;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_zonePlateVAddr_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        zonePlateVAddr_loc_0_fu_298 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_zonePlateVAddr_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_920_p2 == 1'd0))) begin
        Sel_reg_1274 <= {{y_fu_254[7:6]}};
        cmp12_i_reg_1269 <= cmp12_i_fu_931_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        barWidthMinSamples_reg_1228 <= barWidthMinSamples_fu_701_p2;
        barWidth_reg_1238 <= {{add_i_fu_733_p2[13:3]}};
        cmp2_i224_reg_1183 <= cmp2_i224_fu_613_p2;
        conv2_i_i10_i229_reg_1188[1 : 0] <= conv2_i_i10_i229_fu_619_p3[1 : 0];
conv2_i_i10_i229_reg_1188[5 : 4] <= conv2_i_i10_i229_fu_619_p3[5 : 4];
conv2_i_i10_i229_reg_1188[7] <= conv2_i_i10_i229_fu_619_p3[7];
        conv2_i_i10_i234_reg_1198[0] <= conv2_i_i10_i234_fu_633_p3[0];
conv2_i_i10_i234_reg_1198[2] <= conv2_i_i10_i234_fu_633_p3[2];
conv2_i_i10_i234_reg_1198[4] <= conv2_i_i10_i234_fu_633_p3[4];
conv2_i_i10_i234_reg_1198[7] <= conv2_i_i10_i234_fu_633_p3[7];
        conv2_i_i10_i252_cast_cast_cast_cast_reg_1208[0] <= conv2_i_i10_i252_cast_cast_cast_cast_fu_649_p3[0];
conv2_i_i10_i252_cast_cast_cast_cast_reg_1208[2] <= conv2_i_i10_i252_cast_cast_cast_cast_fu_649_p3[2];
        conv2_i_i_i236_cast_cast_reg_1203[0] <= conv2_i_i_i236_cast_cast_fu_641_p3[0];
conv2_i_i_i236_cast_cast_reg_1203[2] <= conv2_i_i_i236_cast_cast_fu_641_p3[2];
conv2_i_i_i236_cast_cast_reg_1203[4] <= conv2_i_i_i236_cast_cast_fu_641_p3[4];
        conv2_i_i_i254_reg_1213[2] <= conv2_i_i_i254_fu_657_p3[2];
conv2_i_i_i254_reg_1213[4] <= conv2_i_i_i254_fu_657_p3[4];
conv2_i_i_i254_reg_1213[7] <= conv2_i_i_i254_fu_657_p3[7];
        icmp_reg_1233 <= icmp_fu_727_p2;
        not_cmp2_i224_reg_1193 <= not_cmp2_i224_fu_627_p2;
        pix_5_reg_1223[6 : 0] <= pix_5_fu_673_p3[6 : 0];
        pix_reg_1218[7] <= pix_fu_665_p3[7];
        rampStart_load_reg_1249 <= rampStart;
        sub_i_i_i_reg_1244 <= sub_i_i_i_fu_763_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_3_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_3_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_3_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_4_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_4_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_4_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_5_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hBarSel_5_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hBarSel_5_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_hdata_flag_0_phi_fu_412_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_920_p2 == 1'd1))) begin
        hdata <= hdata_new_0_fu_286;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hdata_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        hdata_new_0_fu_286 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_hdata_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_0_0_0_0456_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_0_0_0_0_0457_lcssa464_fu_242 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_0_0_0_0456_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_1_0_0_0458_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_0_1_0_0_0459_lcssa467_fu_246 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_1_0_0_0458_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_2_0_0_0460_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_0_2_0_0_0461_lcssa470_fu_250 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_p_0_2_0_0_0460_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_920_p2 == 1'd1))) begin
        rampStart <= add_ln705_fu_954_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_rampVal_3_flag_0_phi_fu_400_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_920_p2 == 1'd1))) begin
        rampVal_1 <= rampVal_3_new_0_fu_314;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_rampVal_2_flag_0_phi_fu_424_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_920_p2 == 1'd1))) begin
        rampVal_2 <= rampVal_2_new_0_fu_270;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_2_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampVal_2_new_0_fu_270 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_2_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_3_new_1_out_ap_vld == 1'b1))) begin
        rampVal_3_new_0_fu_314 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_rampVal_3_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln518_reg_1261 <= trunc_ln518_fu_915_p1;
        y_3_reg_1255 <= y_fu_254;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        vBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_vBarSel_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_zonePlateVAddr_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_zonePlateVAddr;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_920_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bckgndYUV_write = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_bckgndYUV_write;
    end else begin
        bckgndYUV_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_920_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln518_fu_920_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add2_i_fu_685_p2 = (empty_fu_681_p1 + 14'd15);

assign add5_i_fu_711_p2 = (empty_73_fu_707_p1 + 14'd15);

assign add_i_fu_733_p2 = (empty_fu_681_p1 + 14'd7);

assign add_ln518_fu_925_p2 = (y_fu_254 + 16'd1);

assign add_ln705_fu_954_p2 = (motionSpeed + rampStart);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_phi_mux_hdata_flag_0_phi_fu_412_p4 = hdata_flag_0_reg_408;

assign ap_phi_mux_rampVal_2_flag_0_phi_fu_424_p4 = rampVal_2_flag_0_reg_420;

assign ap_phi_mux_rampVal_3_flag_0_phi_fu_400_p4 = rampVal_3_flag_0_reg_396;

assign ap_ready = internal_ap_ready;

assign barHeight_cast_cast_fu_759_p1 = tmp_4_fu_749_p4;

assign barWidthMinSamples_fu_701_p2 = ($signed(p_cast_fu_691_p4) + $signed(10'd1023));

assign bckgndYUV_din = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_bckgndYUV_din;

assign cmp12_i_fu_931_p2 = ((y_fu_254 != 16'd0) ? 1'b1 : 1'b0);

assign cmp2_i224_fu_613_p2 = ((colorFormat == 8'd0) ? 1'b1 : 1'b0);

assign conv2_i_i10_i229_fu_619_p3 = ((cmp2_i224_fu_613_p2[0:0] == 1'b1) ? 8'd255 : 8'd76);

assign conv2_i_i10_i234_fu_633_p3 = ((cmp2_i224_fu_613_p2[0:0] == 1'b1) ? 8'd0 : 8'd149);

assign conv2_i_i10_i252_cast_cast_cast_cast_fu_649_p3 = ((cmp2_i224_fu_613_p2[0:0] == 1'b1) ? 3'd0 : 3'd5);

assign conv2_i_i_i236_cast_cast_fu_641_p3 = ((cmp2_i224_fu_613_p2[0:0] == 1'b1) ? 5'd0 : 5'd21);

assign conv2_i_i_i254_fu_657_p3 = ((cmp2_i224_fu_613_p2[0:0] == 1'b1) ? 8'd255 : 8'd107);

assign empty_73_fu_707_p1 = height[13:0];

assign empty_fu_681_p1 = width[13:0];

assign grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_start = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_432_ap_start_reg;

assign icmp_fu_727_p2 = ((tmp_fu_717_p4 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln518_fu_920_p2 = ((y_fu_254 == height) ? 1'b1 : 1'b0);

assign not_cmp2_i224_fu_627_p2 = (cmp2_i224_fu_613_p2 ^ 1'd1);

assign p_cast_fu_691_p4 = {{add2_i_fu_685_p2[13:4]}};

assign pix_5_fu_673_p3 = ((cmp2_i224_fu_613_p2[0:0] == 1'b1) ? 8'd255 : 8'd128);

assign pix_fu_665_p3 = ((cmp2_i224_fu_613_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign start_out = real_start;

assign sub_i_i_i_fu_763_p2 = ($signed(barHeight_cast_cast_fu_759_p1) + $signed(11'd2047));

assign tmp_4_fu_749_p4 = {{add5_i_fu_711_p2[13:4]}};

assign tmp_fu_717_p4 = {{colorFormat[7:1]}};

assign trunc_ln518_fu_915_p1 = y_fu_254[7:0];

assign zext_ln1212_fu_781_p1 = rampVal;

assign zext_ln1367_fu_797_p1 = vBarSel;

assign zext_ln1493_fu_805_p1 = hBarSel_0;

assign zext_ln1610_fu_821_p1 = hBarSel_3_0;

assign zext_ln1730_fu_833_p1 = vBarSel_1;

assign zext_ln518_fu_841_p1 = hBarSel_5_0;

always @ (posedge ap_clk) begin
    conv2_i_i10_i229_reg_1188[3:2] <= 2'b11;
    conv2_i_i10_i229_reg_1188[6] <= 1'b1;
    conv2_i_i10_i234_reg_1198[1] <= 1'b0;
    conv2_i_i10_i234_reg_1198[3:3] <= 1'b0;
    conv2_i_i10_i234_reg_1198[6:5] <= 2'b00;
    conv2_i_i_i236_cast_cast_reg_1203[1] <= 1'b0;
    conv2_i_i_i236_cast_cast_reg_1203[3] <= 1'b0;
    conv2_i_i10_i252_cast_cast_cast_cast_reg_1208[1] <= 1'b0;
    conv2_i_i_i254_reg_1213[1:0] <= 2'b11;
    conv2_i_i_i254_reg_1213[3:3] <= 1'b1;
    conv2_i_i_i254_reg_1213[6:5] <= 2'b11;
    pix_reg_1218[6:0] <= 7'b0000000;
    pix_5_reg_1223[7] <= 1'b1;
end

endmodule //mpsoc_preset_v_tpg_0_0_tpgBackground
