// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bd_85a6_csc_0_v_hcresampler_core_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stream_in_vresampled_dout,
        stream_in_vresampled_num_data_valid,
        stream_in_vresampled_fifo_cap,
        stream_in_vresampled_empty_n,
        stream_in_vresampled_read,
        HwReg_height_dout,
        HwReg_height_num_data_valid,
        HwReg_height_fifo_cap,
        HwReg_height_empty_n,
        HwReg_height_read,
        HwReg_width_dout,
        HwReg_width_num_data_valid,
        HwReg_width_fifo_cap,
        HwReg_width_empty_n,
        HwReg_width_read,
        p_read,
        stream_in_hresampled_din,
        stream_in_hresampled_num_data_valid,
        stream_in_hresampled_fifo_cap,
        stream_in_hresampled_full_n,
        stream_in_hresampled_write,
        HwReg_width_c21_din,
        HwReg_width_c21_num_data_valid,
        HwReg_width_c21_fifo_cap,
        HwReg_width_c21_full_n,
        HwReg_width_c21_write,
        HwReg_height_c27_din,
        HwReg_height_c27_num_data_valid,
        HwReg_height_c27_fifo_cap,
        HwReg_height_c27_full_n,
        HwReg_height_c27_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] stream_in_vresampled_dout;
input  [4:0] stream_in_vresampled_num_data_valid;
input  [4:0] stream_in_vresampled_fifo_cap;
input   stream_in_vresampled_empty_n;
output   stream_in_vresampled_read;
input  [11:0] HwReg_height_dout;
input  [1:0] HwReg_height_num_data_valid;
input  [1:0] HwReg_height_fifo_cap;
input   HwReg_height_empty_n;
output   HwReg_height_read;
input  [11:0] HwReg_width_dout;
input  [1:0] HwReg_width_num_data_valid;
input  [1:0] HwReg_width_fifo_cap;
input   HwReg_width_empty_n;
output   HwReg_width_read;
input  [0:0] p_read;
output  [23:0] stream_in_hresampled_din;
input  [4:0] stream_in_hresampled_num_data_valid;
input  [4:0] stream_in_hresampled_fifo_cap;
input   stream_in_hresampled_full_n;
output   stream_in_hresampled_write;
output  [11:0] HwReg_width_c21_din;
input  [1:0] HwReg_width_c21_num_data_valid;
input  [1:0] HwReg_width_c21_fifo_cap;
input   HwReg_width_c21_full_n;
output   HwReg_width_c21_write;
output  [11:0] HwReg_height_c27_din;
input  [1:0] HwReg_height_c27_num_data_valid;
input  [1:0] HwReg_height_c27_fifo_cap;
input   HwReg_height_c27_full_n;
output   HwReg_height_c27_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stream_in_vresampled_read;
reg HwReg_height_read;
reg HwReg_width_read;
reg stream_in_hresampled_write;
reg HwReg_width_c21_write;
reg HwReg_height_c27_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    HwReg_height_blk_n;
reg    HwReg_width_blk_n;
reg    HwReg_width_c21_blk_n;
reg    HwReg_height_c27_blk_n;
reg    ap_block_state1;
reg   [11:0] loopHeight_reg_406;
reg   [11:0] HwReg_width_read_reg_411;
wire   [2:0] select_ln685_fu_213_p3;
reg   [2:0] select_ln685_reg_416;
wire   [12:0] loopWidth_fu_233_p2;
reg   [12:0] loopWidth_reg_421;
wire   [0:0] cmp36727_i_fu_239_p2;
reg   [0:0] cmp36727_i_reg_426;
wire   [11:0] y_3_fu_258_p2;
reg   [11:0] y_3_reg_433;
wire    ap_CS_fsm_state2;
reg   [7:0] pixbuf_y_2_load_reg_438;
wire   [0:0] icmp_ln722_fu_253_p2;
reg   [7:0] pixbuf_y_3_load_reg_443;
reg   [7:0] pixbuf_y_4_load_reg_448;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_start;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_done;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_idle;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_ready;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_stream_in_vresampled_read;
wire   [23:0] grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_stream_in_hresampled_din;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_stream_in_hresampled_write;
wire   [7:0] grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_9_out;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_9_out_ap_vld;
wire   [7:0] grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_8_out;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_8_out_ap_vld;
wire   [7:0] grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_7_out;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_7_out_ap_vld;
wire   [7:0] grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_6_out_o;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_6_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_5_out;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_5_out_ap_vld;
wire   [7:0] grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0748795_i_out_o;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0748795_i_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0744792_i_out_o;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0744792_i_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_out_o;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_out1_o;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_out1_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0785_i_out_o;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0785_i_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0480782_i_out_o;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0480782_i_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0751_i_out_o;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0751_i_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0747_i_out_o;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0747_i_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_2_0_0_0741_i_out_o;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_2_0_0_0741_i_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0739_i_out_o;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0739_i_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0_0_0536737_i_out_o;
wire    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0_0_0536737_i_out_o_ap_vld;
reg    grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [7:0] pixbuf_y_4_fu_138;
reg   [7:0] pixbuf_y_3_fu_134;
reg   [7:0] pixbuf_y_2_fu_130;
reg   [7:0] pixbuf_y_1_fu_126;
reg   [7:0] p_0_1_0_0_0748793_lcssa819_i_fu_118;
reg   [7:0] p_0_1_0_0_0744790_lcssa816_i_fu_114;
reg   [7:0] p_lcssa789813_i_fu_110;
reg   [7:0] p_lcssa788810_i_fu_106;
reg   [7:0] p_0_0_0786_lcssa804_i_fu_102;
reg   [7:0] p_0_0_0480783_lcssa798_i_fu_98;
reg   [7:0] p_0_1_0_0_0748_lcssa774_i_fu_94;
reg   [7:0] p_0_1_0_0_0744_lcssa771_i_fu_90;
reg   [7:0] p_0_2_0_0_0740_lcssa765_i_fu_82;
reg   [7:0] p_0_1_0_0_0738_lcssa762_i_fu_78;
reg   [7:0] p_0_0_0_0_0536736_lcssa759_i_fu_74;
reg   [11:0] y_2_fu_70;
wire    ap_CS_fsm_state5;
reg   [7:0] p_0_0_0_0_0536742_lcssa768_i_fu_86;
reg   [7:0] pixbuf_y_fu_122;
wire   [12:0] select_ln720_fu_221_p3;
wire   [12:0] zext_ln720_fu_229_p1;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_start_reg = 1'b0;
end

bd_85a6_csc_0_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2 grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_start),
    .ap_done(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_done),
    .ap_idle(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_idle),
    .ap_ready(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_ready),
    .stream_in_vresampled_dout(stream_in_vresampled_dout),
    .stream_in_vresampled_num_data_valid(5'd0),
    .stream_in_vresampled_fifo_cap(5'd0),
    .stream_in_vresampled_empty_n(stream_in_vresampled_empty_n),
    .stream_in_vresampled_read(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_stream_in_vresampled_read),
    .stream_in_hresampled_din(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_stream_in_hresampled_din),
    .stream_in_hresampled_num_data_valid(5'd0),
    .stream_in_hresampled_fifo_cap(5'd0),
    .stream_in_hresampled_full_n(stream_in_hresampled_full_n),
    .stream_in_hresampled_write(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_stream_in_hresampled_write),
    .pixbuf_y_4(pixbuf_y_4_load_reg_448),
    .pixbuf_y_3(pixbuf_y_3_load_reg_443),
    .pixbuf_y_2(pixbuf_y_2_load_reg_438),
    .pixbuf_y(pixbuf_y_fu_122),
    .p_0_0_0_0_0536742_lcssa768_i(p_0_0_0_0_0536742_lcssa768_i_fu_86),
    .loopWidth(loopWidth_reg_421),
    .select_ln685(select_ln685_reg_416),
    .zext_ln720(HwReg_width_read_reg_411),
    .p_read(p_read),
    .pixbuf_y_9_out(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_9_out),
    .pixbuf_y_9_out_ap_vld(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_9_out_ap_vld),
    .pixbuf_y_8_out(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_8_out),
    .pixbuf_y_8_out_ap_vld(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_8_out_ap_vld),
    .pixbuf_y_7_out(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_7_out),
    .pixbuf_y_7_out_ap_vld(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_7_out_ap_vld),
    .pixbuf_y_6_out_i(pixbuf_y_1_fu_126),
    .pixbuf_y_6_out_o(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_6_out_o),
    .pixbuf_y_6_out_o_ap_vld(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_6_out_o_ap_vld),
    .pixbuf_y_5_out(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_5_out),
    .pixbuf_y_5_out_ap_vld(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_5_out_ap_vld),
    .p_0_1_0_0_0748795_i_out_i(p_0_1_0_0_0748793_lcssa819_i_fu_118),
    .p_0_1_0_0_0748795_i_out_o(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0748795_i_out_o),
    .p_0_1_0_0_0748795_i_out_o_ap_vld(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0748795_i_out_o_ap_vld),
    .p_0_1_0_0_0744792_i_out_i(p_0_1_0_0_0744790_lcssa816_i_fu_114),
    .p_0_1_0_0_0744792_i_out_o(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0744792_i_out_o),
    .p_0_1_0_0_0744792_i_out_o_ap_vld(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0744792_i_out_o_ap_vld),
    .p_out_i(p_lcssa789813_i_fu_110),
    .p_out_o(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_out_o),
    .p_out_o_ap_vld(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_out_o_ap_vld),
    .p_out1_i(p_lcssa788810_i_fu_106),
    .p_out1_o(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_out1_o),
    .p_out1_o_ap_vld(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_out1_o_ap_vld),
    .p_0_0_0785_i_out_i(p_0_0_0786_lcssa804_i_fu_102),
    .p_0_0_0785_i_out_o(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0785_i_out_o),
    .p_0_0_0785_i_out_o_ap_vld(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0785_i_out_o_ap_vld),
    .p_0_0_0480782_i_out_i(p_0_0_0480783_lcssa798_i_fu_98),
    .p_0_0_0480782_i_out_o(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0480782_i_out_o),
    .p_0_0_0480782_i_out_o_ap_vld(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0480782_i_out_o_ap_vld),
    .p_0_1_0_0_0751_i_out_i(p_0_1_0_0_0748_lcssa774_i_fu_94),
    .p_0_1_0_0_0751_i_out_o(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0751_i_out_o),
    .p_0_1_0_0_0751_i_out_o_ap_vld(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0751_i_out_o_ap_vld),
    .p_0_1_0_0_0747_i_out_i(p_0_1_0_0_0744_lcssa771_i_fu_90),
    .p_0_1_0_0_0747_i_out_o(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0747_i_out_o),
    .p_0_1_0_0_0747_i_out_o_ap_vld(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0747_i_out_o_ap_vld),
    .p_0_2_0_0_0741_i_out_i(p_0_2_0_0_0740_lcssa765_i_fu_82),
    .p_0_2_0_0_0741_i_out_o(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_2_0_0_0741_i_out_o),
    .p_0_2_0_0_0741_i_out_o_ap_vld(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_2_0_0_0741_i_out_o_ap_vld),
    .p_0_1_0_0_0739_i_out_i(p_0_1_0_0_0738_lcssa762_i_fu_78),
    .p_0_1_0_0_0739_i_out_o(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0739_i_out_o),
    .p_0_1_0_0_0739_i_out_o_ap_vld(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0739_i_out_o_ap_vld),
    .p_0_0_0_0_0536737_i_out_i(p_0_0_0_0_0536736_lcssa759_i_fu_74),
    .p_0_0_0_0_0536737_i_out_o(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0_0_0536737_i_out_o),
    .p_0_0_0_0_0536737_i_out_o_ap_vld(grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0_0_0536737_i_out_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln722_fu_253_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_start_reg <= 1'b1;
        end else if ((grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_ready == 1'b1)) begin
            grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == HwReg_height_c27_full_n) | (1'b0 == HwReg_width_c21_full_n) | (1'b0 == HwReg_width_empty_n) | (1'b0 == HwReg_height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_2_fu_70 <= 12'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        y_2_fu_70 <= y_3_reg_433;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == HwReg_height_c27_full_n) | (1'b0 == HwReg_width_c21_full_n) | (1'b0 == HwReg_width_empty_n) | (1'b0 == HwReg_height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_read_reg_411 <= HwReg_width_dout;
        cmp36727_i_reg_426 <= cmp36727_i_fu_239_p2;
        loopHeight_reg_406 <= HwReg_height_dout;
        loopWidth_reg_421 <= loopWidth_fu_233_p2;
        select_ln685_reg_416[0] <= select_ln685_fu_213_p3[0];
select_ln685_reg_416[2] <= select_ln685_fu_213_p3[2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0480782_i_out_o_ap_vld == 1'b1))) begin
        p_0_0_0480783_lcssa798_i_fu_98 <= grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0480782_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0785_i_out_o_ap_vld == 1'b1))) begin
        p_0_0_0786_lcssa804_i_fu_102 <= grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0785_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0_0_0536737_i_out_o_ap_vld == 1'b1))) begin
        p_0_0_0_0_0536736_lcssa759_i_fu_74 <= grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_0_0_0_0536737_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp36727_i_reg_426 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_0_0_0_0536742_lcssa768_i_fu_86 <= grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_5_out;
        pixbuf_y_fu_122 <= grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_5_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0739_i_out_o_ap_vld == 1'b1))) begin
        p_0_1_0_0_0738_lcssa762_i_fu_78 <= grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0739_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0744792_i_out_o_ap_vld == 1'b1))) begin
        p_0_1_0_0_0744790_lcssa816_i_fu_114 <= grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0744792_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0747_i_out_o_ap_vld == 1'b1))) begin
        p_0_1_0_0_0744_lcssa771_i_fu_90 <= grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0747_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0748795_i_out_o_ap_vld == 1'b1))) begin
        p_0_1_0_0_0748793_lcssa819_i_fu_118 <= grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0748795_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0751_i_out_o_ap_vld == 1'b1))) begin
        p_0_1_0_0_0748_lcssa774_i_fu_94 <= grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_1_0_0_0751_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_2_0_0_0741_i_out_o_ap_vld == 1'b1))) begin
        p_0_2_0_0_0740_lcssa765_i_fu_82 <= grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_0_2_0_0_0741_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_out1_o_ap_vld == 1'b1))) begin
        p_lcssa788810_i_fu_106 <= grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_out1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_out_o_ap_vld == 1'b1))) begin
        p_lcssa789813_i_fu_110 <= grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_p_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_6_out_o_ap_vld == 1'b1))) begin
        pixbuf_y_1_fu_126 <= grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_6_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_7_out_ap_vld == 1'b1))) begin
        pixbuf_y_2_fu_130 <= grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_7_out;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp36727_i_reg_426 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln722_fu_253_p2 == 1'd0))) begin
        pixbuf_y_2_load_reg_438 <= pixbuf_y_2_fu_130;
        pixbuf_y_3_load_reg_443 <= pixbuf_y_3_fu_134;
        pixbuf_y_4_load_reg_448 <= pixbuf_y_4_fu_138;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_8_out_ap_vld == 1'b1))) begin
        pixbuf_y_3_fu_134 <= grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_8_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_9_out_ap_vld == 1'b1))) begin
        pixbuf_y_4_fu_138 <= grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_pixbuf_y_9_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        y_3_reg_433 <= y_3_fu_258_p2;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_blk_n = HwReg_height_empty_n;
    end else begin
        HwReg_height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_c27_blk_n = HwReg_height_c27_full_n;
    end else begin
        HwReg_height_c27_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == HwReg_height_c27_full_n) | (1'b0 == HwReg_width_c21_full_n) | (1'b0 == HwReg_width_empty_n) | (1'b0 == HwReg_height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_c27_write = 1'b1;
    end else begin
        HwReg_height_c27_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == HwReg_height_c27_full_n) | (1'b0 == HwReg_width_c21_full_n) | (1'b0 == HwReg_width_empty_n) | (1'b0 == HwReg_height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_read = 1'b1;
    end else begin
        HwReg_height_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_blk_n = HwReg_width_empty_n;
    end else begin
        HwReg_width_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_c21_blk_n = HwReg_width_c21_full_n;
    end else begin
        HwReg_width_c21_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == HwReg_height_c27_full_n) | (1'b0 == HwReg_width_c21_full_n) | (1'b0 == HwReg_width_empty_n) | (1'b0 == HwReg_height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_c21_write = 1'b1;
    end else begin
        HwReg_width_c21_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == HwReg_height_c27_full_n) | (1'b0 == HwReg_width_c21_full_n) | (1'b0 == HwReg_width_empty_n) | (1'b0 == HwReg_height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_read = 1'b1;
    end else begin
        HwReg_width_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == HwReg_height_c27_full_n) | (1'b0 == HwReg_width_c21_full_n) | (1'b0 == HwReg_width_empty_n) | (1'b0 == HwReg_height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln722_fu_253_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln722_fu_253_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        stream_in_hresampled_write = grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_stream_in_hresampled_write;
    end else begin
        stream_in_hresampled_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        stream_in_vresampled_read = grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_stream_in_vresampled_read;
    end else begin
        stream_in_vresampled_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((1'b0 == HwReg_height_c27_full_n) | (1'b0 == HwReg_width_c21_full_n) | (1'b0 == HwReg_width_empty_n) | (1'b0 == HwReg_height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln722_fu_253_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((cmp36727_i_reg_426 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln722_fu_253_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign HwReg_height_c27_din = HwReg_height_dout;

assign HwReg_width_c21_din = HwReg_width_dout;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((1'b0 == HwReg_height_c27_full_n) | (1'b0 == HwReg_width_c21_full_n) | (1'b0 == HwReg_width_empty_n) | (1'b0 == HwReg_height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign cmp36727_i_fu_239_p2 = ((loopWidth_fu_233_p2 == 13'd0) ? 1'b1 : 1'b0);

assign grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_start = grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_ap_start_reg;

assign icmp_ln722_fu_253_p2 = ((y_2_fu_70 == loopHeight_reg_406) ? 1'b1 : 1'b0);

assign loopWidth_fu_233_p2 = (select_ln720_fu_221_p3 + zext_ln720_fu_229_p1);

assign select_ln685_fu_213_p3 = ((p_read[0:0] == 1'b1) ? 3'd0 : 3'd5);

assign select_ln720_fu_221_p3 = ((p_read[0:0] == 1'b1) ? 13'd0 : 13'd5);

assign stream_in_hresampled_din = grp_v_hcresampler_core_2_Pipeline_VITIS_LOOP_724_2_fu_180_stream_in_hresampled_din;

assign y_3_fu_258_p2 = (y_2_fu_70 + 12'd1);

assign zext_ln720_fu_229_p1 = HwReg_width_dout;

always @ (posedge ap_clk) begin
    select_ln685_reg_416[1] <= 1'b0;
end

endmodule //bd_85a6_csc_0_v_hcresampler_core_2
