# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mpsoc_preset/mpsoc_preset.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset || ORIG_REF_NAME==mpsoc_preset} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_zynq_ultra_ps_e_0_0/mpsoc_preset_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==mpsoc_preset_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/mpsoc_preset_v_tpg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_v_tpg_0_0 || ORIG_REF_NAME==mpsoc_preset_v_tpg_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_v_tc_0_0/mpsoc_preset_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_v_tc_0_0 || ORIG_REF_NAME==mpsoc_preset_v_tc_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_v_axi4s_vid_out_0_0/mpsoc_preset_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==mpsoc_preset_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_clk_wiz_0_0/mpsoc_preset_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_clk_wiz_0_0 || ORIG_REF_NAME==mpsoc_preset_clk_wiz_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_xbar_0/mpsoc_preset_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_xbar_0 || ORIG_REF_NAME==mpsoc_preset_xbar_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_ps8_0_axi_periph_0/mpsoc_preset_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_ps8_0_axi_periph_0 || ORIG_REF_NAME==mpsoc_preset_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_rst_ps8_0_187M_0/mpsoc_preset_rst_ps8_0_187M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_rst_ps8_0_187M_0 || ORIG_REF_NAME==mpsoc_preset_rst_ps8_0_187M_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/mpsoc_preset_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_system_ila_0_0 || ORIG_REF_NAME==mpsoc_preset_system_ila_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_system_ila_1_0/mpsoc_preset_system_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_system_ila_1_0 || ORIG_REF_NAME==mpsoc_preset_system_ila_1_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_xlconstant_0_0/mpsoc_preset_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_xlconstant_0_0 || ORIG_REF_NAME==mpsoc_preset_xlconstant_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_xlconstant_0_1/mpsoc_preset_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_xlconstant_0_1 || ORIG_REF_NAME==mpsoc_preset_xlconstant_0_1} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_auto_ds_0/mpsoc_preset_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_auto_ds_0 || ORIG_REF_NAME==mpsoc_preset_auto_ds_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_auto_pc_0/mpsoc_preset_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_auto_pc_0 || ORIG_REF_NAME==mpsoc_preset_auto_pc_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_auto_ds_1/mpsoc_preset_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_auto_ds_1 || ORIG_REF_NAME==mpsoc_preset_auto_ds_1} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_auto_pc_1/mpsoc_preset_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_auto_pc_1 || ORIG_REF_NAME==mpsoc_preset_auto_pc_1} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_v_proc_ss_0_0/mpsoc_preset_v_proc_ss_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_v_proc_ss_0_0 || ORIG_REF_NAME==mpsoc_preset_v_proc_ss_0_0} -quiet] -quiet

# XDC: d:/dp/zcu106/tpg_dp_live/vivado/tpg_dp_live/tpg_dp_live.gen/sources_1/bd/mpsoc_preset/mpsoc_preset_ooc.xdc
