#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Script generated by Vivado on Fri Nov 15 11:01:34 +0800 2024
# SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
#
# Tool Version Limit: 2023.05 
#
# Filename     : mpsoc_preset.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : mpsoc_preset.sh
#                mpsoc_preset.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                mpsoc_preset.sh [-reset_run]
#                mpsoc_preset.sh [-reset_log]
#                mpsoc_preset.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the Xilinx simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'mpsoc_preset.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname axi_infrastructure_v1_1_0 -libname axi_vip_v1_1_14 -libname zynq_ultra_ps_e_vip_v1_0_14 -libname xil_defaultlib -libname xbip_utils_v3_0_10 -libname axi_utils_v2_0_6 -libname xbip_pipe_v3_0_6 -libname xbip_dsp48_wrapper_v3_0_4 -libname xbip_dsp48_addsub_v3_0_6 -libname xbip_bram18k_v3_0_6 -libname mult_gen_v12_0_18 -libname floating_point_v7_0_20 -libname xbip_dsp48_mult_v3_0_6 -libname xbip_dsp48_multadd_v3_0_6 -libname div_gen_v5_1_19 -libname v_tpg_v8_2_2 -libname axi_lite_ipif_v3_0_4 -libname v_tc_v6_2_6 -libname v_tc_v6_1_13 -libname v_vid_in_axi4s_v4_0_9 -libname v_axi4s_vid_out_v4_0_16 -libname generic_baseblocks_v2_1_0 -libname axi_register_slice_v2_1_28 -libname fifo_generator_v13_2_8 -libname axi_data_fifo_v2_1_27 -libname axi_crossbar_v2_1_29 -libname lib_cdc_v1_0_2 -libname proc_sys_reset_v5_0_13 -libname gigantic_mux -libname xlconstant_v1_1_7 -libname axi_protocol_converter_v2_1_28 -libname axi_clock_converter_v2_1_27 -libname blk_mem_gen_v8_4_6 -libname axi_dwidth_converter_v2_1_28 -libname v_csc_v1_1_7 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_14 zynq_ultra_ps_e_vip_v1_0_14 xil_defaultlib xbip_utils_v3_0_10 axi_utils_v2_0_6 xbip_pipe_v3_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_18 floating_point_v7_0_20 xbip_dsp48_mult_v3_0_6 xbip_dsp48_multadd_v3_0_6 div_gen_v5_1_19 v_tpg_v8_2_2 axi_lite_ipif_v3_0_4 v_tc_v6_2_6 v_tc_v6_1_13 v_vid_in_axi4s_v4_0_9 v_axi4s_vid_out_v4_0_16 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_28 fifo_generator_v13_2_8 axi_data_fifo_v2_1_27 axi_crossbar_v2_1_29 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 gigantic_mux xlconstant_v1_1_7 axi_protocol_converter_v2_1_28 axi_clock_converter_v2_1_27 blk_mem_gen_v8_4_6 axi_dwidth_converter_v2_1_28 v_csc_v1_1_7)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "mpsoc_preset.sh - Script generated by export_simulation (Vivado v2023.1 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./mpsoc_preset.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "D:/program/Xilinx2023/Vivado/2023.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "D:/program/Xilinx2023/Vivado/2023.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "D:/program/Xilinx2023/Vivado/2023.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm $xmvhdl_opts \
  "D:/program/Xilinx2023/Vivado/2023.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_14 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ed63/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work zynq_ultra_ps_e_vip_v1_0_14 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_zynq_ultra_ps_e_0_0/sim/mpsoc_preset_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_am_addmul_16ns_1s_16ns_17_4_1.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_CTRL_s_axi.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_fifo_w24_d16_S.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_flow_control_loop_pipe_sequential_init.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_hls_deadlock_detection_unit.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_hls_deadlock_idx0_monitor.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_mac_muladd_16ns_6s_24s_24_4_1.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_mac_muladd_16ns_7ns_13ns_23_4_1.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_mac_muladd_16ns_7s_16ns_23_4_1.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_mac_muladd_16ns_8ns_23ns_24_4_1.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_mac_muladd_16ns_8s_23s_24_4_1.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_mac_muladd_16s_16s_16ns_16_4_1.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_mul_11ns_13ns_23_1_1.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_mul_16ns_6ns_21_1_1.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_mul_16ns_8s_24_1_1.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_mul_20s_9ns_28_1_1.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_MultiPixStream2AXIvideo.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_mux_3_2_8_1_1.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_mux_5_3_9_1_1.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_reg_ap_uint_10_s.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_reg_int_s.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_reg_unsigned_short_s.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_regslice_both.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_start_for_MultiPixStream2AXIvideo_U0.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_start_for_tpgForeground_U0.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_blkYuv_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_bluYuv_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_DPtpgBarArray_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_DPtpgBarSelRgb_CEA_b_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_DPtpgBarSelRgb_CEA_g_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_DPtpgBarSelRgb_CEA_r_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_DPtpgBarSelYuv_601_u_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_DPtpgBarSelYuv_601_v_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_DPtpgBarSelYuv_601_y_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_DPtpgBarSelYuv_709_u_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_DPtpgBarSelYuv_709_v_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_DPtpgBarSelYuv_709_y_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_grnYuv_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_redYuv_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_tpgBarSelRgb_b_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_tpgBarSelRgb_g_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_tpgBarSelRgb_r_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_tpgBarSelYuv_u_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_tpgBarSelYuv_v_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_tpgBarSelYuv_y_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_tpgCheckerBoardArray_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_tpgSinTableArray_9bit_0_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_tpgSinTableArray_9bit_1_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_tpgSinTableArray_9bit_2_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_tpgSinTableArray_9bit_3_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_tpgSinTableArray_9bit_4_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_tpgSinTableArray_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_tpgTartanBarArray_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2_whiYuv_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgForeground.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_729_2.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_tpgForeground_Pipeline_VITIS_LOOP_729_2_whiYuv_2_ROM_AUTO_1R.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_urem_11ns_4ns_3_15_1.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_v_tpgHlsDataFlow.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog/mpsoc_preset_v_tpg_0_0_v_tpg.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xbip_utils_v3_0_10 $xmvhdl_opts \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_utils_v2_0_6 $xmvhdl_opts \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_pipe_v3_0_6 $xmvhdl_opts \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_dsp48_wrapper_v3_0_4 $xmvhdl_opts \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_dsp48_addsub_v3_0_6 $xmvhdl_opts \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_bram18k_v3_0_6 $xmvhdl_opts \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work mult_gen_v12_0_18 $xmvhdl_opts \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work floating_point_v7_0_20 $xmvhdl_opts \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_dsp48_mult_v3_0_6 $xmvhdl_opts \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/xbip_dsp48_mult_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_dsp48_multadd_v3_0_6 $xmvhdl_opts \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work div_gen_v5_1_19 $xmvhdl_opts \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/div_gen_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work v_tpg_v8_2_2 $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/v_tpg_v8_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/sim/mpsoc_preset_v_tpg_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_lite_ipif_v3_0_4 $xmvhdl_opts \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work v_tc_v6_2_6 $xmvhdl_opts \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/0350/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tc_0_0/sim/mpsoc_preset_v_tc_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work v_tc_v6_1_13 $xmvhdl_opts \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work v_vid_in_axi4s_v4_0_9 $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work v_axi4s_vid_out_v4_0_16 $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/c523/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_axi4s_vid_out_0_0/sim/mpsoc_preset_v_axi4s_vid_out_0_0.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_clk_wiz_0_0/mpsoc_preset_clk_wiz_0_0_clk_wiz.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_clk_wiz_0_0/mpsoc_preset_clk_wiz_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work generic_baseblocks_v2_1_0 $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_28 $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/87d1/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_8 $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/c97d/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_2_8 $xmvhdl_opts \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_8 $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_data_fifo_v2_1_27 $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/fab7/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_crossbar_v2_1_29 $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f8f3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_xbar_0/sim/mpsoc_preset_xbar_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_2 $xmvhdl_opts \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_13 $xmvhdl_opts \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_rst_ps8_0_187M_0/sim/mpsoc_preset_rst_ps8_0_187M_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/sim/bd_9390.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/ip/ip_0/sim/bd_9390_ila_lib_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work gigantic_mux $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/e87a/hdl/gigantic_mux_v1_0_cntr.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/ip/ip_1/bd_9390_g_inst_0_gigantic_mux.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/ip/ip_1/sim/bd_9390_g_inst_0.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/sim/mpsoc_preset_system_ila_0_0.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_system_ila_1_0/bd_0/sim/bd_53c1.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_system_ila_1_0/bd_0/ip/ip_0/sim/bd_53c1_ila_lib_0.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_system_ila_1_0/sim/mpsoc_preset_system_ila_1_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xlconstant_v1_1_7 $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/b0f2/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_xlconstant_0_0/sim/mpsoc_preset_xlconstant_0_0.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_xlconstant_0_1/sim/mpsoc_preset_xlconstant_0_1.v" \
  "../../../bd/mpsoc_preset/sim/mpsoc_preset.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_protocol_converter_v2_1_28 $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/8c02/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_clock_converter_v2_1_27 $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/29db/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work blk_mem_gen_v8_4_6 $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/bb55/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_dwidth_converter_v2_1_28 $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/08ae/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_auto_ds_0/sim/mpsoc_preset_auto_ds_0.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_auto_pc_0/sim/mpsoc_preset_auto_pc_0.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_auto_ds_1/sim/mpsoc_preset_auto_ds_1.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_auto_pc_1/sim/mpsoc_preset_auto_pc_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work v_csc_v1_1_7 $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_proc_ss_0_0/bd_0/ip/ip_0/hdl/v_csc_v1_1_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"$ref_dir/../../../bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/ec67/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/f805/hdl" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_v_tpg_0_0/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/30ef" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/1b7e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/122e/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/affe/hdl/verilog" +incdir+"../../../../tpg_dp_live.gen/sources_1/bd/mpsoc_preset/ipshared/20d0/hdl/verilog" +incdir+"D:/program/Xilinx2023/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_proc_ss_0_0/bd_0/ip/ip_0/sim/bd_85a6_csc_0.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_proc_ss_0_0/bd_0/sim/bd_85a6.v" \
  "../../../bd/mpsoc_preset/ip/mpsoc_preset_v_proc_ss_0_0/sim/mpsoc_preset_v_proc_ss_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.mpsoc_preset xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.mpsoc_preset -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file


  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log mpsoc_preset_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./mpsoc_preset.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: mpsoc_preset.sh [-help]\n\
Usage: mpsoc_preset.sh [-step]\n\
Usage: mpsoc_preset.sh [-lib_map_path]\n\
Usage: mpsoc_preset.sh [-reset_run]\n\
Usage: mpsoc_preset.sh [-reset_log]\n\
Usage: mpsoc_preset.sh [-keep_index]\n\
Usage: mpsoc_preset.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
